name: wikiner37
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py37_1
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=hf484d3e_0
  - openssl=1.0.2p=h14c3975_0
  - pip=10.0.1=py37_0
  - python=3.7.0=hc3d631a_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.2.0=py37_0
  - sqlite=3.24.0=h84994c4_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.31.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - pip:
    - alabaster==0.7.11
    - allennlp==0.6.1
    - asn1crypto==0.24.0
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - aws-xray-sdk==0.95
    - awscli==1.16.20
    - babel==2.6.0
    - boto==2.49.0
    - boto3==1.9.10
    - botocore==1.12.10
    - cffi==1.11.2
    - chardet==3.0.4
    - click==6.7
    - colorama==0.3.9
    - conllu==0.11
    - cookies==2.2.1
    - cryptography==2.3.1
    - cymem==1.31.2
    - cytoolz==0.9.0.1
    - dill==0.2.8.2
    - docker==3.5.0
    - docker-pycreds==0.3.0
    - docutils==0.14
    - ecdsa==0.13
    - editdistance==0.5.2
    - flaky==3.4.0
    - flask==0.12.4
    - flask-cors==3.0.3
    - future==0.16.0
    - gevent==1.3.5
    - greenlet==0.4.15
    - h5py==2.8.0
    - idna==2.7
    - imagesize==1.1.0
    - itsdangerous==0.24
    - jinja2==2.10
    - jmespath==0.9.3
    - jsondiff==1.1.1
    - jsonnet==0.10.0
    - jsonpickle==1.0
    - markupsafe==1.0
    - mock==2.0.0
    - more-itertools==4.3.0
    - moto==1.3.4
    - msgpack==0.5.6
    - msgpack-numpy==0.4.3.2
    - murmurhash==0.28.0
    - nltk==3.3
    - numpy==1.15.2
    - numpydoc==0.8.0
    - overrides==1.9
    - packaging==17.1
    - parsimonious==0.8.0
    - pbr==4.2.0
    - plac==0.9.6
    - pluggy==0.7.1
    - preshed==1.0.1
    - protobuf==3.6.1
    - py==1.6.0
    - pyaml==17.12.1
    - pyasn1==0.4.4
    - pycparser==2.19
    - pycryptodome==3.6.6
    - pygments==2.2.0
    - pyparsing==2.2.1
    - pytest==3.8.1
    - python-dateutil==2.7.3
    - python-jose==2.0.2
    - pytz==2017.3
    - pyyaml==3.13
    - regex==2017.4.5
    - requests==2.19.1
    - responses==0.9.0
    - rsa==3.4.2
    - s3transfer==0.1.13
    - scikit-learn==0.19.2
    - scipy==1.1.0
    - six==1.11.0
    - snowballstemmer==1.2.1
    - spacy==2.0.12
    - sphinx==1.8.1
    - sphinxcontrib-websupport==1.1.0
    - tensorboardx==1.2
    - thinc==6.10.3
    - toolz==0.9.0
    - torch==0.4.1.post2
    - tqdm==4.26.0
    - ujson==1.35
    - unidecode==1.0.22
    - urllib3==1.23
    - websocket-client==0.53.0
    - werkzeug==0.14.1
    - wrapt==1.10.11
    - xmltodict==0.11.0
prefix: /home/fariz/workspace/miniconda3/envs/wikiner37